services:
  shop-checker:
    build: .
    init: true
    shm_size: "1gb"
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./data
        target: /app/data
        bind:
          create_host_path: false
